### ISSUE TITLE
FATAL: Error verifying developer key: Failed to create input stream: Connection timed out (Read failed)

### ISSUE THREAD

**Issue by RuchiDhore** [kinow/testlink-java-api#121]
I am trying to integrate Jenkins with TestLink. Both of them are on separate machines.
Referred following links to integrate it and a pdf with all steps:
https://wiki.jenkins.io/display/JENKINS/TestLink+Plugin

When I try to run the job in Jenkins, I get following error:
Preparing TestLink client API.
Using TestLink URL: http://IP_Address:Port/TestLink_1.9.19/lib/api/xmlrpc/v1/xmlrpc.php

FATAL: Error verifying developer key: Failed to create input stream: Connection timed out (Read failed)
br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIException: Error verifying developer key: Failed to create input stream: Connection timed out (Read failed)
	at br.eti.kinoshita.testlinkjavaapi.MiscService.checkDevKey(MiscService.java:64)
	at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.<init>(TestLinkAPI.java:149)
	at hudson.plugins.testlink.TestLinkBuilder.getTestLinkSite(TestLinkBuilder.java:331)
	at hudson.plugins.testlink.TestLinkBuilder.perform(TestLinkBuilder.java:206)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1810)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: org.apache.xmlrpc.XmlRpcException: Failed to create input stream: Connection timed out (Read failed)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:99)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:152)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
	at br.eti.kinoshita.testlinkjavaapi.BaseService.executeXmlRpcCall(BaseService.java:83)
	at br.eti.kinoshita.testlinkjavaapi.MiscService.checkDevKey(MiscService.java:61)
	... 12 more
Caused by: java.net.SocketException: Connection timed out (Read failed)
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:92)
	... 21 more
ERROR: Error communicating with TestLink. Check your TestLink configuration.
Finished: FAILURE

TestLink version: 1.9.19
TestLink plugin version: 3.16

What is going wrong? Please help!

**Comment by kinow** [comment]
Hi @RuchiDhore ,

>Connection timed out

This could be a connectivity issue. Check IP, port, HTTP vs. HTTPS, etc.

**Comment by RuchiDhore** [comment]
If I access this address in browser: http://IP_Address:Port/TestLink_1.9.19/lib/api/xmlrpc/v1, I am able to see all files under v1 directory. Tried changing http to https, in that I dont get any error however build fails..

**Comment by kinow** [comment]
>If I access this address in browser: http://IP_Address:Port/TestLink_1.9.19/lib/api/xmlrpc/v1, I am able to see all files under v1 directory. 

Just to make sure. You are testing that URL from the same host where Jenkins is running?

Also take a look at similar issues reported before. I remember some of them had good pointers about what could be causing this issue in your environment: https://github.com/kinow/testlink-java-api/issues?utf8=%E2%9C%93&q=developer+key

**Comment by RuchiDhore** [comment]
I was able to connect through API and code when I changed the link to http://IP_Address:Port/testlink/lib/api/xmlrpc/v1/xmlrpc.php

There seems to be some network issue on Jenkins

Thanks!
