### ISSUE TITLE
Testlink cannot overwrite existing testplans

### ISSUE THREAD

**Issue by cambiph** [kinow/testlink-java-api#30]
Hello,

I upgraded to Testlink 1.9.9 and Java api 1.9.8-1.
The code handling the Testlink communication did not change but now I get the following stack trace:

```
br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIException: There's already a Test Suite with name: Loopbaancheques
    at br.eti.kinoshita.testlinkjavaapi.BaseService.checkResponseError(BaseService.java:123)
    at br.eti.kinoshita.testlinkjavaapi.BaseService.executeXmlRpcCall(BaseService.java:91)
    at br.eti.kinoshita.testlinkjavaapi.TestSuiteService.createTestSuite(TestSuiteService.java:86)
    at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.createTestSuite(TestLinkAPI.java:636)
    at be.vdab.commons.test.util.testlink.TestlinkDataManager.getTestSuite(TestlinkDataManager.java:173)
    at be.vdab.commons.test.util.testlink.TestlinkDataManager.createTestCase(TestlinkDataManager.java:150)
    at be.vdab.commons.test.util.testlink.TestlinkDataManager.getTestCase(TestlinkDataManager.java:137)
    at be.vdab.commons.test.util.testlink.TestlinkCommunicator.sendToTestLink(TestlinkCommunicator.java:43)
    at be.vdab.commons.test.junit.rules.SendToTestLinkWatcher.succeeded(SendToTestLinkWatcher.java:20)
    at org.junit.rules.TestWatcher.succeededQuietly(TestWatcher.java:75)
    at org.junit.rules.TestWatcher.access$100(TestWatcher.java:46)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:56)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

It looks like an existing test plan cannot be appended or overwritten. 
As far as I know this worked in the past.

**Comment by kinow** [comment]
Sorry for the long - really really long - delay. This is from the PHP API. This Java API is simply a facade to the PHP API.

See
- https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/8bb4c60fd753433cefc5c09dfc160e6041d6b81a/lib/functions/testsuite.class.php#L1616
