### ISSUE TITLE
Fatal error integrating Jenkins and TestLink

### ISSUE THREAD

**Issue by br1970** [kinow/testlink-java-api#36]
Hi, I'm trying to setup Jenkins and TestLink using your plugin, and I keep getting the Fatal error below. I have followed the steps to setup TestLink and Jenkins according to the tutorial on: http://tupilabs.com/books/jenkins-testlink-plugin-tutorial/en/book.pdf

My configuration is:
Win 7
Jenkins 1.509.4
TestLink 1.9.9
Jenkins-TestLink plugin 3.10

I get the following error when I run the build in Jenkins (and the build fails to finish):

FATAL: br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.<init>(Ljava/net/URL;Ljava/lang/String;)V
java.lang.NoSuchMethodError: br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.<init>(Ljava/net/URL;Ljava/lang/String;)V
    at hudson.plugins.testlink.TestLinkBuilder.getTestLinkSite(TestLinkBuilder.java:307)
    at hudson.plugins.testlink.TestLinkBuilder.perform(TestLinkBuilder.java:186)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:780)
    at hudson.model.Build$BuildExecution.build(Build.java:199)
    at hudson.model.Build$BuildExecution.doRun(Build.java:160)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:565)
    at hudson.model.Run.execute(Run.java:1592)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:237)

Any help would be appreciated!!

**Comment by kinow** [comment]
Sorry for not answering this old issue. Closing now as it's quite outdated, but feel free to re-open if you still have this problem. This issue is more likely an issue for the Jenkins plugin IMO.
