### ISSUE TITLE
Cannot locate configuration source testlinkjavaapi.properties

### ISSUE THREAD

**Issue by phatso** [kinow/testlink-java-api#58]
I am getting the Error verifying developer key: Failed to parse server's response: Expected methodResponse element, got br
After some debugging I found it was being caused by the above error.  Here is the stacktrace:
09:18:15.294 [pool-1-thread-2] DEBUG b.e.k.testlinkjavaapi.TestLinkAPI - Cannot locate configuration source testlinkjavaapi.properties
org.apache.commons.configuration.ConfigurationException: Cannot locate configuration source testlinkjavaapi.properties
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:249) ~[commons-configuration-1.7.jar:1.7]
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:229) ~[commons-configuration-1.7.jar:1.7]
	at org.apache.commons.configuration.AbstractFileConfiguration.<init>(AbstractFileConfiguration.java:149) ~[commons-configuration-1.7.jar:1.7]
	at org.apache.commons.configuration.PropertiesConfiguration.<init>(PropertiesConfiguration.java:252) ~[commons-configuration-1.7.jar:1.7]
	at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.createApplicationConfiguration(TestLinkAPI.java:157) [testlink-java-api-1.9.13-0.jar:na]
	at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.<init>(TestLinkAPI.java:130) [testlink-java-api-1.9.13-0.jar:na]
	at ec.ncsc.mil.sit.testlink.TestLinkIntegration.<init>(TestLinkIntegration.java:37) [classes/:na]
	at ec.ncsc.mil.sit.form810c.Form810cTest.setUp(Form810cTest.java:62) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit-4.11.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.11.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit-4.11.jar:na]
	at com.github.webdriverextensions.junitrunner.WebDriverRunner.runChild(WebDriverRunner.java:272) [webdriverextensions-1.5.0.jar:na]
	at com.github.webdriverextensions.junitrunner.WebDriverRunner.runChild(WebDriverRunner.java:86) [webdriverextensions-1.5.0.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:na]
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387) [surefire-junit47-2.18.1.jar:2.18.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
09:18:15.344 [pool-1-thread-2] DEBUG b.e.k.testlinkjavaapi.TestLinkAPI - 'xmlrpc.connectionTimeout' doesn't map to an existing object
java.util.NoSuchElementException: 'xmlrpc.connectionTimeout' doesn't map to an existing object
	at org.apache.commons.configuration.AbstractConfiguration.getInt(AbstractConfiguration.java:822) ~[commons-configuration-1.7.jar:1.7]
	at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.createXmlRpcClientConfiguration(TestLinkAPI.java:184) [testlink-java-api-1.9.13-0.jar:na]
	at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.<init>(TestLinkAPI.java:133) [testlink-java-api-1.9.13-0.jar:na]
	at ec.ncsc.mil.sit.testlink.TestLinkIntegration.<init>(TestLinkIntegration.java:37) [classes/:na]
	at ec.ncsc.mil.sit.form810c.Form810cTest.setUp(Form810cTest.java:62) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit-4.11.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.11.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit-4.11.jar:na]
	at com.github.webdriverextensions.junitrunner.WebDriverRunner.runChild(WebDriverRunner.java:272) [webdriverextensions-1.5.0.jar:na]
	at com.github.webdriverextensions.junitrunner.WebDriverRunner.runChild(WebDriverRunner.java:86) [webdriverextensions-1.5.0.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:na]
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387) [surefire-junit47-2.18.1.jar:2.18.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

I looked in the project root but cannot find this properties file.  Where can i find this properties file?
I am using TL 1.9.13 with api version 1.9.13-0

Thanks Brian

**Comment by kinow** [comment]
The testlinkjavaapi.properties file is located at src/test/resources/

ps: there is a "Find File" feature in GitHub. If you clicked on this button in the repository main page, and then started typing it, GitHub will show matching files in the project ;-)
