### ISSUE TITLE
getTestCaseCustomFieldExecutionValue not working

### ISSUE THREAD

**Issue by gajo4256** [kinow/testlink-java-api#59]
Hi,

I have seen already issues regarding getTestCaseCustomFieldExecutionValue [here](https://github.com/kinow/testlink-java-api/issues/35) and [here](https://github.com/kinow/testlink-java-api/issues/32). First one seems still to be opened, the second one closed. We are using testLink 1.9.13 and still the same error is present:

```
Caused by: org.apache.xmlrpc.client.XmlRpcClientException: Failed to parse server's response: Expected methodResponse element, got pre
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:188)
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
    at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
    at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
    at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
    at br.eti.kinoshita.testlinkjavaapi.BaseService.executeXmlRpcCall(BaseService.java:90)
    at br.eti.kinoshita.testlinkjavaapi.TestCaseService.getTestCaseCustomFieldExecutionValue(TestCaseService.java:689)
    ... 30 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 6; Expected methodResponse element, got pre
    at org.apache.xmlrpc.parser.XmlRpcResponseParser.startElement(XmlRpcResponseParser.java:101)
    at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:186)
    ... 39 more
```

Is there any update on this? Can maybe someone point me to this method exposed on TestLink interface itself? I would try to write it on my own then and see if it works

**Comment by kinow** [comment]
>Caused by: org.apache.xmlrpc.client.XmlRpcClientException: Failed to parse server's response: Expected methodResponse element, got pre

If I remember well, I would see similar message when my end point was not returning the XML-RPC response.

If the problem persists, feel free to re-open. Try to include as much information as possible to reproduce the issue, such as TestLink version, API version, code snippet if possible, etc.

Thanks
