### ISSUE TITLE
 FATAL: Error verifying developer key: Failed to parse server's response: Content is not allowed in prolog.

### ISSUE THREAD

**Issue by sai-tirunagiri** [kinow/testlink-java-api#72]
Hi,

Any help on the below error?

FATAL: Error verifying developer key: Failed to parse server's response: Content is not allowed in prolog.
br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIException: Error verifying developer key: Failed to parse server's response: Content is not allowed in prolog.
    at br.eti.kinoshita.testlinkjavaapi.MiscService.checkDevKey(MiscService.java:64)
    at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.<init>(TestLinkAPI.java:146)
    at hudson.plugins.testlink.TestLinkBuilder.getTestLinkSite(TestLinkBuilder.java:331)
    at hudson.plugins.testlink.TestLinkBuilder.perform(TestLinkBuilder.java:206)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
    at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.build(MavenModuleSetBuild.java:919)
    at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:671)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
    at hudson.model.Run.execute(Run.java:1741)
    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: org.apache.xmlrpc.client.XmlRpcClientException: Failed to parse server's response: Content is not allowed in prolog.
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:188)
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
    at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
    at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
    at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
    at br.eti.kinoshita.testlinkjavaapi.BaseService.executeXmlRpcCall(BaseService.java:90)
    at br.eti.kinoshita.testlinkjavaapi.MiscService.checkDevKey(MiscService.java:61)
    ... 12 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:186)
    ... 21 more
ERROR: Error communicating with TestLink. Check your TestLink configuration.

**Comment by kinow** [comment]
Hi @sai-tirunagiri 

Probably worth double-checking the URL you are using. Perhaps the endpoint URL is incorrect

**Comment by sai-tirunagiri** [comment]
http://*******/testlink/lib/api/xmlrpc/v1/xmlrpc.php

This would be the URL I am using currently. Don't know what exactly the problem is.

**Comment by kinow** [comment]
What version of TestLink are you using?

**Comment by sai-tirunagiri** [comment]
Its 1.9.15

**Comment by kinow** [comment]
Reproduced the issue on 1.9.15, though I can't really say what's wrong yet.

**Comment by abogdanovqa** [comment]
The problem is on testlink side. 

There is a workaround (from https://foliovision.com/2007/05/xml-rpc-server-wordpress-error):
Add the following lines to lib/api/xmlrpc/v1/xmlrpc.php

```
// Some browser-embedded clients send cookies. We don't want them.
$_COOKIE = array();

$GLOBALS['HTTP_RAW_POST_DATA'] = file_get_contents("php://input");
```

**Comment by kinow** [comment]
Thanks @abogdanovqa !

I noticed some weird errors in the logs, but thought it could be because I was running PHP 7. Tried with PHP 5, and got the same error. Now at least it makes sense.

**Comment by Diptman** [comment]
Any updates on this issue ? I'm also facing similar problem. Logs are as below:

```
FATAL: Error verifying developer key: Failed to parse server's response: Content is not allowed in prolog.
br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIException: Error verifying developer key: Failed to parse server's response: Content is not allowed in prolog.
	at br.eti.kinoshita.testlinkjavaapi.MiscService.checkDevKey(MiscService.java:64)
	at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.<init>(TestLinkAPI.java:146)
	at hudson.plugins.testlink.TestLinkBuilder.getTestLinkSite(TestLinkBuilder.java:331)
	at hudson.plugins.testlink.TestLinkBuilder.perform(TestLinkBuilder.java:206)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.build(MavenModuleSetBuild.java:939)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:890)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:544)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: org.apache.xmlrpc.client.XmlRpcClientException: Failed to parse server's response: Content is not allowed in prolog.
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:188)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
	at br.eti.kinoshita.testlinkjavaapi.BaseService.executeXmlRpcCall(BaseService.java:90)
	at br.eti.kinoshita.testlinkjavaapi.MiscService.checkDevKey(MiscService.java:61)
	... 12 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:186)
	... 21 more
ERROR: Error communicating with TestLink. Check your TestLink configuration.
```

**Comment by kinow** [comment]
Hi @Diptman the issue has been reported to TestLink. There is a workaround that was posted here before too. Take a look at the comments, and feel free to chime in here to say whether that works for you too, or in the TestLink issue tracker :-)

**Comment by Diptman** [comment]
@kinow : workaround worked for me ! Thanks! 
Thanks @abogdanovqa

**Comment by kinow** [comment]
Excellent, thanks for the feedback @Diptman ! Hopefully it will work for others too.

**Comment by kinow** [comment]
1.9.16 released. We can test it soon and check if a 1.9.16-0 could be cut (if anyone has time to give it a shot, otherwise I may have time to set up the dev env again in a few days)

**Comment by kinow** [comment]
Version 1.9.16-0 to be released in the next hours.

Tested the following:

* Started a temp MySQL Server with `https://github.com/kinow/testlink-java-api/issues/77`
* Downloaded testlink-1.9.16.tar.gz, and unpacked
* Started a temp PHP Server with `cd testlink-1.9.16 && php -S 0.0.0.0:8888`

Followed the installation procedure, then created a project, and generated my admin user API Key. Then tested with the following code:

```
package br.eti.kinoshita.testlinkjavaapi;

import java.net.URL;

public class Test {

    public static void main(String[] args) throws Exception {
        TestLinkAPI api = new TestLinkAPI(new URL("http://localhost:8888/lib/api/xmlrpc/v1/xmlrpc.php"), "280540a10fb8a11561888f963397b3b2");
        System.out.println(api.getProjects());
    }
    
}

```

And got:

```
Mar 19, 2017 11:30:31 PM org.apache.commons.beanutils.FluentPropertyBeanIntrospector introspect
INFO: Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
[Lbr.eti.kinoshita.testlinkjavaapi.model.TestProject;@456a973f

```

**Comment by Diptman** [comment]
@rangercoder There is workaround posted by abogdanovqa above my post, that helped me.

**Comment by rangercoder** [comment]
@Diptman Thanks for your reply.I have test it on http://localhost/testlink/lib/api/xmlrpc/v1/xmlrpc.php that jenkins connnect with testlink is ok now.But my qc testlink server is cloud server,such as https://.../lib/api/xmlrpc/v1/xmlrpc.php which is apper your some issue.And you can see https://github.com/kinow/testlink-java-api/issues/104 which is my issue's details.
Could you sure?(I have use testlink:1.9.6 )
Thx.

**Comment by rangercoder** [comment]
@Diptman sorry,it's my cloud server environment error,and I have solve it.
